language: node_js
node_js: stable
sudo: false

git:
  submodules: false

script:
  - npm test

addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test

matrix:
  include:
    - env: TEST_SUITE=node-canvas
      script: "export CXX=g++-4.8 && npm i jsdom canvas && npm test"
      addons:
        hosts:
          - web-platform.test
          - www.web-platform.test
          - www1.web-platform.test
          - www2.web-platform.test
          - xn--n8j6ds53lwwkrqhv28a.web-platform.test
          - xn--lve-6lad.web-platform.test
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libcairo2-dev
            - libjpeg8-dev
            - libpango1.0-dev
            - libgif-dev
            - build-essential
